[[language]]
name = "elixir"
formatter = { command = "mix", args = ["format", "-"] }
[[language]]
name = "heex"
auto-format = true
formatter = { command = "mix", args = [
  "format",
  "--stdin-filename",
  "a.heex",
  "-",
] }
